//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailleur
{
    using System;
    using System.Collections.Generic;
    
    public partial class commande
    {
        public int id { get; set; }
        public System.DateTime datecommander { get; set; }
        public System.DateTime datelivraison { get; set; }
        public int idclient { get; set; }
        public string typeTissu { get; set; }
        public int longTissu { get; set; }
        public string model { get; set; }
        public int prixPaye { get; set; }
        public int montantAnvace { get; set; }
        public string etat { get; set; }
    }
}
