//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailleur
{
    using System;
    using System.Collections.Generic;
    
    public partial class femme
    {
        public int id { get; set; }
        public int taille { get; set; }
        public int longzupe { get; set; }
        public int longrobe { get; set; }
        public int longtaillebasse { get; set; }
        public int long3_4 { get; set; }
        public int idmesure { get; set; }
    }
}
