//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailleur
{
    using System;
    using System.Collections.Generic;
    
    public partial class homme
    {
        public int id { get; set; }
        public int longdemisaison { get; set; }
        public int cout { get; set; }
        public int idmesure { get; set; }
    }
}
