//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tailleur
{
    using System;
    using System.Collections.Generic;
    
    public partial class mesure
    {
        public int id { get; set; }
        public int idclient { get; set; }
        public int epole { get; set; }
        public int poitrine { get; set; }
        public int manchelong { get; set; }
        public int manchecourte { get; set; }
        public int tourefesse { get; set; }
        public int longpentalon { get; set; }
        public int tourecuisse { get; set; }
        public int tourebras { get; set; }
        public int ceinture { get; set; }
    }
}
